export const courseData = [
  {
    name: 'Css to the rescue',
    slug: 'css-to-the-rescue',
    url: '/css-to-the-rescue',
    teachers: ['Sanne', 'Vasilis'],
    dateStart: '06-02-2023',
    dateEnd: '06-03-2023',
    weeks: 4,
    classRating: Number,
    difficultyRating: Number,
    explanationRating: Number,
    personalUnderstanding: String,
    prevCourse: null,
    nextCourse: '/web-app-from-scratch',
  },
  {
    name: 'Webapp from Scratch',
    slug: 'web-app-from-scratch',
    url: '/web-app-from-scratch',
    teachers: ['Robert', 'Joost'],
    dateStart: '06-02-2023',
    dateEnd: '06-03-2023',
    weeks: 4,
    classRating: Number,
    difficultyRating: Number,
    explanationRating: Number,
    personalUnderstanding: String,
    prevCourse: 'css-to-the-rescue',
    nextCourse: '/progressive-web-app',
  },
  {
    name: 'Progressive Web App',
    slug: 'progressive-web-app',
    url: '/progressive-web-app',
    teachers: ['Janno', 'Declan'],
    dateStart: '20-03-2023',
    dateEnd: '03-03-2023',
    weeks: 3,
    classRating: Number,
    difficultyRating: Number,
    explanationRating: Number,
    personalUnderstanding: String,
    prevCourse: '/web-app-from-scratch',
    nextCourse: '/browser-technologies',
  },
  {
    name: 'Browser Technologies',
    slug: 'browser-technologies',
    url: '/browser-technologies',
    teachers: ['Vasillis', 'Peter-Paul'],
    dateStart: '20-03-2023',
    dateEnd: '03-03-2023',
    weeks: 3,
    classRating: Number,
    difficultyRating: Number,
    explanationRating: Number,
    personalUnderstanding: String,
    prevCourse: 'progressive-web-app',
    nextCourse: null,
  },
];
