export const courseData = [
  {
    id: 1,
    name: "Css to the rescue",
    slug: "css-to-the-rescue",
    url: "/css-to-the-rescue",
    teachers: ["Sanne", "Vasilis"],
    dateStart: "2023-02-06",
    dateEnd: "2023-03-06",
    weeks: 4,
    classRating: Number,
    difficultyRating: Number,
    explanationRating: Number,
    personalUnderstanding: String,
    prevCourse: '/start',
    nextCourse: "/web-app-from-scratch",
  },
  {
    id: 2,
    name: "Webapp from Scratch",
    slug: "web-app-from-scratch",
    url: "/web-app-from-scratch",
    teachers: ["Robert", "Joost"],
    dateStart: "2023-02-06",
    dateEnd: "2023-03-06",
    weeks: 4,
    classRating: Number,
    difficultyRating: Number,
    explanationRating: Number,
    personalUnderstanding: String,
    prevCourse: "/css-to-the-rescue",
    nextCourse: "/progressive-web-apps",
  },
  {
    id: 3,
    name: "Progressive Web App",
    slug: "progressive-web-apps",
    url: "/progressive-web-apps",
    teachers: ["Janno", "Declan"],
    dateStart: "2023-03-20",
    dateEnd: "2023-04-02",
    weeks: 3,
    classRating: Number,
    difficultyRating: Number,
    explanationRating: Number,
    personalUnderstanding: String,
    prevCourse: "/web-app-from-scratch",
    nextCourse: "/browser-technologies",
  },
  {
    id: 4,
    name: "Browser Technologies",
    slug: "browser-technologies",
    url: "/browser-technologies",
    teachers: ["Vasillis", "Peter-Paul"],
    dateStart: "2023-03-20",
    dateEnd: "2023-04-02",
    weeks: 3,
    classRating: Number,
    difficultyRating: Number,
    explanationRating: Number,
    personalUnderstanding: String,
    prevCourse: "/progressive-web-apps",
    nextCourse: "/end",
  },
];